Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xg_reg = xgb.XGBRegressor(eval_metric=mean_absolute_error, n_estimators = 100, subsample = 0.9)
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(xg_reg, X_train, Y_train, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)

xg_reg.fit(X_train, Y_train)
xgb.to_graphviz(xg_reg, num_trees=0)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m xg_reg [38;5;241m=[39m xgb[38;5;241m.[39mXGBRegressor(eval_metric[38;5;241m=[39m[43mmean_absolute_error[49m, n_estimators [38;5;241m=[39m [38;5;241m100[39m, subsample [38;5;241m=[39m [38;5;241m0.9[39m)
[1;32m      2[0m cv [38;5;241m=[39m RepeatedKFold(n_splits[38;5;241m=[39m[38;5;241m10[39m, n_repeats[38;5;241m=[39m[38;5;241m3[39m, random_state[38;5;241m=[39m[38;5;241m1[39m)
[1;32m      3[0m n_scores [38;5;241m=[39m cross_val_score(xg_reg, X_train, Y_train, scoring[38;5;241m=[39m[38;5;124m'[39m[38;5;124mneg_mean_absolute_error[39m[38;5;124m'[39m, cv[38;5;241m=[39mcv, n_jobs[38;5;241m=[39m[38;5;241m-[39m[38;5;241m1[39m)

[0;31mNameError[0m: name 'mean_absolute_error' is not defined
NameError: name 'mean_absolute_error' is not defined

